services:
  dev:
    &default-dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /Users/dmitryshusterman/WebstormProjects/spicetime-architecture-setup/spicetime-architecture:/app
      - /Users/dmitryshusterman/WebstormProjects/spicetime-architecture-setup/spicetime-architecture/logs:/app/logs
    ports:
      - "3000:3000"    # App port
    environment:
      - NODE_ENV=development
    profiles:
      - dev            # Standard development mode
    command: ["pnpm", "dev"]

  dev-debug:
    <<: *default-dev
    ports:
      - "3000:3000"    # App debug port
      - "9229:9229"    # Debugging port
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.js"]
    profiles:
      - dev-debug      # Debugging mode