services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app               # Project directory
      - ./logs:/app/logs     # Logs directory
    ports:
      - "${DEV_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    command: ["pnpm", "dev"]

  dev-debug:
    <<: *default-dev
    ports:
      - "${DEV_PORT:-3000}:3000"
      - "9229:9229"
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.js"]
    profiles:
      - dev-debug