services:
  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=test
    ports:
      - "9229:9229" # Debugging port for test-debug only
    command: ["pnpm", "test:all"]
    profiles:
      - run-all-tests         # Executes the entire test suite

  test-watch:
    extends: test
    command: ["pnpm", "test:watch"]
    profiles:
      - test-watch-mode       # Runs tests in watch mode for development

  test-debug:
    extends: test
    command: ["node", "--inspect-brk=0.0.0.0:9229", "node_modules/vitest/vitest.mjs"]
    profiles:
      - debug-tests           # Enables test debugging with inspector