schema: src/graphql/schema.graphql
documents: src/**/*.graphql
extensions:
  codegen:
    generates:
      src/generated/:
        preset: client
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo