name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-check:
    name: Lint and Format Changes
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Identify changed files using Git diff
      - name: List changed files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt

      # Step 5: Lint and format specific files
      - name: Lint and format all changed files
        run: |
          # Parse the changed files
          changed_files=( $(cat changed-files.txt) )
          for file in "${changed_files[@]}"
          do
            if [[ $file == *.js || $file == *.jsx || $file == *.ts || $file == *.tsx ]]; then
              echo "Running ESLint and Prettier on $file"
              eslint --fix "$file"
              prettier --write "$file"
            elif [[ $file == *.json || $file == *.md || $file == *.yml || $file == *.yaml ]]; then
              echo "Running Prettier on $file"
              prettier --write "$file"
            fi
          done